export const listProduct_ = [
  {
    id: "1",
    name: "1 Cestinha decorada de açai",
    description: "Um pedacinho de céu em cada mordida! ⭐",
    value: "R$26,58",
    size: ["P", "M", "G"],
    flavor: ["Açai", "Sorvete"],
    border: ["Nutella", "Chocolate", "Chocolate Branco"],
    follow_up: ["Granulado Colorido", "Granulado de Chocolate"],
    fruit: ["Morango", "Banana"],
  },
  {
    id: "2",
    name: "2 Cestinha decorada de açai",
    description: "Um pedacinho de céu em cada mordida! ⭐",
    value: "R$26,58",
    size: ["P", "M", "G"],
    flavor: ["Açai", "Sorvete"],
    border: ["Nutella", "Chocolate", "Chocolate Branco"],
    follow_up: ["Granulado Colorido", "Granulado de Chocolate"],
    fruit: ["Morango", "Banana"],
  },
  {
    id: "3",
    name: "3 Cestinha decorada de açai",
    description: "Um pedacinho de céu em cada mordida! ⭐",
    value: "R$26,58",
    size: ["P", "M", "G"],
    flavor: ["Açai", "Sorvete"],
    border: ["Nutella", "Chocolate", "Chocolate Branco"],
    follow_up: ["Granulado Colorido", "Granulado de Chocolate"],
    fruit: ["Morango", "Banana"],
  },
  {
    id: "4",
    name: "4 Cestinha decorada de açai",
    description: "Um pedacinho de céu em cada mordida! ⭐",
    value: "R$26,58",
    size: ["P", "M", "G"],
    flavor: ["Açai", "Sorvete"],
    border: ["Nutella", "Chocolate", "Chocolate Branco"],
    follow_up: ["Granulado Colorido", "Granulado de Chocolate"],
    fruit: ["Morango", "Banana"],
  },
  {
    id: "5",
    name: "5 Cestinha decorada de açai",
    description: "Um pedacinho de céu em cada mordida! ⭐",
    value: "R$26,58",
    size: ["P", "M", "G"],
    flavor: ["Açai", "Sorvete"],
    border: ["Nutella", "Chocolate", "Chocolate Branco"],
    follow_up: ["Granulado Colorido", "Granulado de Chocolate"],
    fruit: ["Morango", "Banana"],
  },
];